import { button } from 'leva'

export const createControlsSchema = ({
  startDims,
  maxDims,
  selectedMaterialKey,
  materials,
  isDevMaterialVisible,
  onResetMaterialPresets,
}) => ({
  width: { value: startDims.x, min: startDims.x, max: maxDims.x, step: 0.01 },
  height: { value: startDims.y, min: startDims.y, max: maxDims.y, step: 0.01 },
  depth: { value: startDims.z, min: startDims.z, max: maxDims.z, step: 0.01 },
  shelves: { value: 1, min: 0, max: 4, step: 1 },
  dividers: { value: 1, min: 0, max: 4, step: 1 },
  edgeOffset: { value: 0.05, min: 0, max: 0.2, step: 0.01 },
  slotOffset: { value: 0.01, min: 0.015, max: 0.15, step: 0.001 },
  interlockSlotsEnabled: { value: true },
  interlockSlotClearance: { value: 0.0001, min: 0, max: 0.001, step: 0.00001, render: get => get('interlockSlotsEnabled') },
  interlockSlotLengthFactor: { value: 1.8, min: 1, max: 6, step: 0.1, render: get => get('interlockSlotsEnabled') },
  bevelEnabled: { value: false },
  bevelSize: { value: 0.0002, min: 0, max: 0.0008, step: 0.00001, render: get => get('bevelEnabled') },
  bevelThickness: { value: 0.0002, min: 0, max: 0.0008, step: 0.00001, render: get => get('bevelEnabled') },
  bevelSegments: { value: 2, min: 1, max: 8, step: 1, render: get => get('bevelEnabled') },
  activeMaterialKey: { value: selectedMaterialKey || 'Painted', options: ['Painted', 'Brushed', 'Chrome', 'MATCAP', 'Wireframe', 'UVDebug'], render: () => false },
  material: {
    value: materials.mat_PaintedMetal,
    options: {
      Brushed: materials.mat_Brushed,
      Chrome: materials.mat_Chrome,
      Painted: materials.mat_PaintedMetal,
      MATCAP: materials.mat_MATCAP,
      Wireframe: materials.mat_Wireframe,
      UVDebug: materials.mat_UVDebug,
    },
  },
  paintedMetal_Colour: { value: '#526982' },
  showProps: true,
  showDevTools: false,
  pbr_roughness: { value: 0.3, min: 0, max: 1, step: 0.01, render: get => isDevMaterialVisible(get, 'Brushed') },
  pbr_metalness: { value: 1, min: 0, max: 1, step: 0.01, render: get => isDevMaterialVisible(get, 'Brushed') },
  pbr_bumpScale: { value: 0.05, min: 0, max: 1, step: 0.01, render: get => isDevMaterialVisible(get, 'Brushed') },
  pbr_noiseScale: { value: 1, min: 0.1, max: 8, step: 0.1, render: get => isDevMaterialVisible(get, 'Brushed') },
  pbr_noiseX1: { value: 10, min: 0.001, max: 10, step: 0.1, render: get => isDevMaterialVisible(get, 'Brushed') },
  pbr_noiseY1: { value: 1, min: 0.001, max: 10, step: 0.1, render: get => isDevMaterialVisible(get, 'Brushed') },
  pbr_noiseX2: { value: 4.9, min: 0.1, max: 10, step: 0.1, render: get => isDevMaterialVisible(get, 'Brushed') },
  pbr_noiseY2: { value: 10, min: 0.1, max: 10, step: 0.1, render: get => isDevMaterialVisible(get, 'Brushed') },
  chrome_roughness: { value: 0.15, min: 0, max: 1, step: 0.01, render: get => isDevMaterialVisible(get, 'Chrome') },
  chrome_metalness: { value: 1, min: 0, max: 1, step: 0.01, render: get => isDevMaterialVisible(get, 'Chrome') },
  chrome_bumpScale: { value: 0.04, min: 0, max: 1, step: 0.01, render: get => isDevMaterialVisible(get, 'Chrome') },
  chrome_noiseScale: { value: 1, min: 0.1, max: 8, step: 0.1, render: get => isDevMaterialVisible(get, 'Chrome') },
  chrome_noiseX1: { value: 10, min: 0.001, max: 10, step: 0.1, render: get => isDevMaterialVisible(get, 'Chrome') },
  chrome_noiseY1: { value: 1, min: 0.001, max: 10, step: 0.1, render: get => isDevMaterialVisible(get, 'Chrome') },
  chrome_noiseX2: { value: 4.9, min: 0.1, max: 10, step: 0.1, render: get => isDevMaterialVisible(get, 'Chrome') },
  chrome_noiseY2: { value: 10, min: 0.1, max: 10, step: 0.1, render: get => isDevMaterialVisible(get, 'Chrome') },
  painted_roughness: { value: 1, min: 0, max: 1, step: 0.01, render: get => isDevMaterialVisible(get, 'Painted') },
  painted_metalness: { value: 0.2, min: 0, max: 1, step: 0.01, render: get => isDevMaterialVisible(get, 'Painted') },
  painted_bumpScale: { value: 0.08, min: 0, max: 1, step: 0.01, render: get => isDevMaterialVisible(get, 'Painted') },
  painted_noiseScale: { value: 1, min: 0.1, max: 8, step: 0.1, render: get => isDevMaterialVisible(get, 'Painted') },
  painted_noiseX1: { value: 10, min: 0.001, max: 10, step: 0.1, render: get => isDevMaterialVisible(get, 'Painted') },
  painted_noiseY1: { value: 1, min: 0.001, max: 10, step: 0.1, render: get => isDevMaterialVisible(get, 'Painted') },
  painted_noiseX2: { value: 4.9, min: 0.1, max: 10, step: 0.1, render: get => isDevMaterialVisible(get, 'Painted') },
  painted_noiseY2: { value: 10, min: 0.1, max: 10, step: 0.1, render: get => isDevMaterialVisible(get, 'Painted') },
  resetMaterialPresets: button(onResetMaterialPresets),
  lightPos: { value: [0.14, 0.19, 0.12], render: get => get('showDevTools') },
  lightTarget: { value: [-0.2210000000000003, -0.7, -0.007999999999999612], render: get => get('showDevTools') },
  intensity: { value: 0.005, min: 0, max: 10, render: get => get('showDevTools') },
  mapSize: { value: 1024, options: [512, 1024, 2048], render: get => get('showDevTools') },
  near: { value: 0.001, min: 0, max: 10, render: get => get('showDevTools') },
  far: { value: 10, min: 0.1, max: 100, render: get => get('showDevTools') },
  ui3dDimsScaleMin: { value: 0.45, min: 0.1, max: 3, step: 0.01, render: get => get('showDevTools') },
  ui3dDimsScaleMax: { value: 4.2, min: 0.2, max: 30, step: 0.01, render: get => get('showDevTools') },
  ui3dButtonsScaleMin: { value: 0.45, min: 0.1, max: 3, step: 0.01, render: get => get('showDevTools') },
  ui3dButtonsScaleMax: { value: 5, min: 0.2, max: 30, step: 0.01, render: get => get('showDevTools') },
  contactShadowPos: { value: [0.086, -0.15, 0], render: get => get('showDevTools') },
  idleDelaySeconds: { value: 3, min: 0, max: 20, step: 0.5, render: get => get('showDevTools') },
  idleRotateSpeed: { value: 0.15, min: 0.05, max: 3, step: 0.05, render: get => get('showDevTools') },
  idleRampSeconds: { value: 5, min: 0.2, max: 12, step: 0.1, render: get => get('showDevTools') },
})
