/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/console_2.glb --transform --types 
Files: public/console_2.glb [22.66MB] > D:\Projects\_scripts\web_dev\parametric_furniture_viewer\parasys-mvp\console_2-transformed.glb [2.3MB] (90%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane025: THREE.Mesh
    Plane025_1: THREE.Mesh
    BOOKS003: THREE.Mesh
    BOOKS004: THREE.Mesh
    BOOKS008: THREE.Mesh
    HOLDER: THREE.Mesh
    Plane011: THREE.Mesh
    Plane011_1: THREE.Mesh
    GOBLETS: THREE.Mesh
    BOWL: THREE.Mesh
    Circle003: THREE.Mesh
    Circle003_1: THREE.Mesh
    Circle003_2: THREE.Mesh
    Circle003_3: THREE.Mesh
    Plane017: THREE.Mesh
    Plane017_1: THREE.Mesh
    BOOKS009: THREE.Mesh
  }
  materials: {
    ['BOOK COVER MATERIAL.002']: THREE.MeshStandardMaterial
    ['PAPER MATERIAL']: THREE.MeshStandardMaterial
    ['BOOK COVER MATERIAL.005']: THREE.MeshStandardMaterial
    ['BOOK COVER MATERIAL.001']: THREE.MeshStandardMaterial
    ['BOOK COVER MATERIAL.003']: THREE.MeshStandardMaterial
    ['WOOD MATERIAL.001']: THREE.MeshStandardMaterial
    ['METAL MATERIAL.002']: THREE.MeshPhysicalMaterial
    ['WOOD MATERIAL']: THREE.MeshPhysicalMaterial
    ['METAL MATERIAL.001']: THREE.MeshPhysicalMaterial
    ['MARBLE MATERIAL.02']: THREE.MeshStandardMaterial
    ['FABRIC MATERIAL']: THREE.MeshStandardMaterial
    ['METAL MATERIAL.002']: THREE.MeshPhysicalMaterial
    ['MARBLE MATERIAL.02']: THREE.MeshStandardMaterial
    ['GLASS MATERIAL']: THREE.MeshPhysicalMaterial
    ['PANITING MATERIAL']: THREE.MeshPhysicalMaterial
    ['WHITE PANEL.001']: THREE.MeshStandardMaterial
    ['BOOK COVER MATERIAL.004']: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/console_2-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.37, 1.177, -0.17]}>
        <mesh geometry={nodes.Plane025.geometry} material={materials['BOOK COVER MATERIAL.002']} />
        <mesh geometry={nodes.Plane025_1.geometry} material={materials['PAPER MATERIAL']} />
      </group>
      <mesh geometry={nodes.BOOKS003.geometry} material={materials['BOOK COVER MATERIAL.005']} position={[0.37, 1.177, -0.17]} />
      <mesh geometry={nodes.BOOKS004.geometry} material={materials['BOOK COVER MATERIAL.001']} position={[0.37, 1.177, -0.17]} />
      <mesh geometry={nodes.BOOKS008.geometry} material={materials['BOOK COVER MATERIAL.003']} position={[0.37, 1.177, -0.17]} />
      <mesh geometry={nodes.HOLDER.geometry} material={materials['WOOD MATERIAL.001']} position={[0.37, 1.177, -0.17]} />
      <group position={[0.116, 0.645, 0.303]}>
        <mesh geometry={nodes.Plane011.geometry} material={materials['METAL MATERIAL.002']} />
        <mesh geometry={nodes.Plane011_1.geometry} material={materials['WOOD MATERIAL']} />
      </group>
      <mesh geometry={nodes.GOBLETS.geometry} material={materials['METAL MATERIAL.001']} position={[-0.31, 1.426, 0.028]} />
      <mesh geometry={nodes.BOWL.geometry} material={materials['MARBLE MATERIAL.02']} position={[0.701, 1.174, 0.053]} />
      <group position={[0.882, 1.174, -0.09]}>
        <mesh geometry={nodes.Circle003.geometry} material={materials['FABRIC MATERIAL']} />
        <mesh geometry={nodes.Circle003_1.geometry} material={materials['METAL MATERIAL.002']} />
        <mesh geometry={nodes.Circle003_2.geometry} material={materials['MARBLE MATERIAL.02']} />
        <mesh geometry={nodes.Circle003_3.geometry} material={materials['GLASS MATERIAL']} />
      </group>
      <group position={[-0.208, 1.176, -0.285]}>
        <mesh geometry={nodes.Plane017.geometry} material={materials['PANITING MATERIAL']} />
        <mesh geometry={nodes.Plane017_1.geometry} material={materials['WHITE PANEL.001']} />
      </group>
      <mesh geometry={nodes.BOOKS009.geometry} material={materials['BOOK COVER MATERIAL.004']} position={[-0.786, 1.176, -0.027]} />
    </group>
  )
}

useGLTF.preload('/console_2-transformed.glb')
