/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/console_1.glb --transform --types 
Files: public/console_1.glb [21.86MB] > D:\Projects\_scripts\web_dev\parametric_furniture_viewer\parasys-mvp\console_1-transformed.glb [2.23MB] (90%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    BOOKS001: THREE.Mesh
    BOOKS002: THREE.Mesh
    BOOKS003: THREE.Mesh
    BOOKS006: THREE.Mesh
    BOOKS008: THREE.Mesh
    HOLDER: THREE.Mesh
    CONSOLE001: THREE.Mesh
    DOOR_HANDLES: THREE.Mesh
    GOBLETS: THREE.Mesh
    BOWL: THREE.Mesh
    LAMP003: THREE.Mesh
    LAMP005: THREE.Mesh
    PAINTING001: THREE.Mesh
    PAINTING004: THREE.Mesh
    BOOKS010: THREE.Mesh
  }
  materials: {
    ['PAPER MATERIAL']: THREE.MeshStandardMaterial
    ['BOOK COVER MATERIAL.002']: THREE.MeshStandardMaterial
    ['BOOK COVER MATERIAL.005']: THREE.MeshStandardMaterial
    ['BOOK COVER MATERIAL.001']: THREE.MeshStandardMaterial
    ['BOOK COVER MATERIAL.003']: THREE.MeshStandardMaterial
    ['WOOD MATERIAL.001']: THREE.MeshStandardMaterial
    ['WOOD MATERIAL']: THREE.MeshPhysicalMaterial
    ['METAL MATERIAL.002']: THREE.MeshPhysicalMaterial
    ['METAL MATERIAL.001']: THREE.MeshPhysicalMaterial
    ['MARBLE MATERIAL.02']: THREE.MeshStandardMaterial
    ['GLASS MATERIAL']: THREE.MeshPhysicalMaterial
    ['FABRIC MATERIAL']: THREE.MeshStandardMaterial
    ['WHITE PANEL.001']: THREE.MeshStandardMaterial
    ['PANITING MATERIAL']: THREE.MeshPhysicalMaterial
    ['BOOK COVER MATERIAL.004']: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/console_1-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.BOOKS001.geometry} material={materials['PAPER MATERIAL']} position={[0.37, 1.177, -0.17]} />
      <mesh geometry={nodes.BOOKS002.geometry} material={materials['BOOK COVER MATERIAL.002']} position={[0.37, 1.177, -0.17]} />
      <mesh geometry={nodes.BOOKS003.geometry} material={materials['BOOK COVER MATERIAL.005']} position={[0.37, 1.177, -0.17]} />
      <mesh geometry={nodes.BOOKS006.geometry} material={materials['BOOK COVER MATERIAL.001']} position={[0.37, 1.177, -0.17]} />
      <mesh geometry={nodes.BOOKS008.geometry} material={materials['BOOK COVER MATERIAL.003']} position={[0.37, 1.177, -0.17]} />
      <mesh geometry={nodes.HOLDER.geometry} material={materials['WOOD MATERIAL.001']} position={[0.37, 1.177, -0.17]} />
      <mesh geometry={nodes.CONSOLE001.geometry} material={materials['WOOD MATERIAL']} position={[-0.001, 0.645, -0.002]} />
      <mesh geometry={nodes.DOOR_HANDLES.geometry} material={materials['METAL MATERIAL.002']} position={[-0.56, 0.645, 0.322]} />
      <mesh geometry={nodes.GOBLETS.geometry} material={materials['METAL MATERIAL.001']} position={[-0.31, 1.426, 0.028]} />
      <mesh geometry={nodes.BOWL.geometry} material={materials['MARBLE MATERIAL.02']} position={[0.701, 1.174, 0.053]} />
      <mesh geometry={nodes.LAMP003.geometry} material={materials['GLASS MATERIAL']} position={[0.882, 1.174, -0.09]} />
      <mesh geometry={nodes.LAMP005.geometry} material={materials['FABRIC MATERIAL']} position={[0.882, 1.174, -0.09]} />
      <mesh geometry={nodes.PAINTING001.geometry} material={materials['WHITE PANEL.001']} position={[-0.208, 1.176, -0.285]} />
      <mesh geometry={nodes.PAINTING004.geometry} material={materials['PANITING MATERIAL']} position={[-0.208, 1.176, -0.285]} />
      <mesh geometry={nodes.BOOKS010.geometry} material={materials['BOOK COVER MATERIAL.004']} position={[-0.786, 1.176, -0.027]} />
    </group>
  )
}

useGLTF.preload('/console_1-transformed.glb')
