/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/furniture_4.glb --transform --types 
Files: public/furniture_4.glb [12.58MB] > D:\Projects\_scripts\web_dev\parametric_furniture_viewer\parasys-mvp\furniture_4-transformed.glb [1.43MB] (89%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    L_Medieval_chair: THREE.Mesh
    R_Medieval_chair: THREE.Mesh
    CBack_Medieval_chair: THREE.Mesh
    COrnament_Medieval_chair: THREE.Mesh
    COrnament_Medieval_chair_001: THREE.Mesh
    CSeat_Medieval_chair: THREE.Mesh
    LOrnament_Medieval_chair: THREE.Mesh
    LOrnament_Medieval_chair_001: THREE.Mesh
    ROrnament_Medieval_chair: THREE.Mesh
    ROrnament_Medieval_chair_001: THREE.Mesh
  }
  materials: {
    chair: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/furniture_5-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.L_Medieval_chair.geometry} material={materials.chair} />
      <mesh geometry={nodes.R_Medieval_chair.geometry} material={materials.chair} />
      <mesh geometry={nodes.CBack_Medieval_chair.geometry} material={materials.chair} />
      <mesh geometry={nodes.COrnament_Medieval_chair.geometry} material={materials.chair} />
      <mesh geometry={nodes.COrnament_Medieval_chair_001.geometry} material={materials.chair} />
      <mesh geometry={nodes.CSeat_Medieval_chair.geometry} material={materials.chair} />
      <mesh geometry={nodes.LOrnament_Medieval_chair.geometry} material={materials.chair} />
      <mesh geometry={nodes.LOrnament_Medieval_chair_001.geometry} material={materials.chair} />
      <mesh geometry={nodes.ROrnament_Medieval_chair.geometry} material={materials.chair} />
      <mesh geometry={nodes.ROrnament_Medieval_chair_001.geometry} material={materials.chair} />
    </group>
  )
}

useGLTF.preload('/furniture_5-transformed.glb')
