/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\sheetMetal_1.glb --transform --types 
Files: .\public\sheetMetal_1.glb [2.77MB] > D:\Projects\_scripts\web_dev\parametric_furniture_viewer\parasys-mvp\sheetMetal_1-transformed.glb [395.02KB] (86%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    StainlessSheet: THREE.Mesh
  }
  materials: {
    ['Stainless Steel']: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/sheetMetal_1-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.StainlessSheet.geometry} material={materials['Stainless Steel']} />
    </group>
  )
}

useGLTF.preload('/sheetMetal_1-transformed.glb')
