/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Props_1.glb --transform --types 
Files: Props_1.glb [3.27MB] > D:\Projects\_scripts\web_dev\parametric_furniture_viewer\parasys-mvp\public\Props_1-transformed.glb [623.17KB] (81%)
*/

import * as THREE from 'three'
// import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    vase_7001: THREE.Mesh
    Cylinder004: THREE.Mesh
    Cylinder003: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cube004: THREE.Mesh
    Cube004_1: THREE.Mesh
    Cube003: THREE.Mesh
    Cube003_1: THREE.Mesh
    Cube008: THREE.Mesh
  }
  materials: {
    ['ceremic.001']: THREE.MeshStandardMaterial
    ['Clay Orange']: THREE.MeshStandardMaterial
    ['White Clay Procedural']: THREE.MeshStandardMaterial
    Porcelain: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Props_1-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.vase_7001.geometry} material={materials['ceremic.001']} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials['Clay Orange']} rotation={[0, -0.857, 0]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['White Clay Procedural']} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials.Porcelain} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Cube004_1.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Cube003_1.geometry} material={materials['Material.005']} />
    </group>
  )
}

useGLTF.preload('/Props_1-transformed.glb')
